name: Deploy App

on: 
    push:
        branches: [main]
    pull_request:
        branches: [main]
        types: [opened, synchronize]   

jobs:
    lint:
        runs-on: ubuntu-20.04
        steps: 
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint   
              
    build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions-checkout@v3
              with:
                fetch-depth: 0
            - uses: actions-setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - uses: actions/upload-artifact@v3
              with:
                name: dist
                path: dist    