name: Deployment Pipeline
# Las Actions de cada dependencia externa a GITHUB la podemos encontrar en el MARKETPLACE de GITHUB
on:
    push: # Evento de GIT q espera
        branches: [main] # Mi rama principal

jobs:

    lint:
      runs-on: ubuntu-20.04
      steps:
         - uses: actions/checkout@v3
           with:
              fetch-depth: 0
         - uses: actions/setup-node@v3
           with:
              node-version: 18
         - name: Install dependencies
           run: npm ci
         - name: Lint
           run: npm run lint

    build:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v3
          with:
             fetch-depth: 0
        - uses: actions/setup-node@v3
          with:
             node-version: 18
        - name: Install dependencies
          run: npm ci
        - name: Build
          run: npm run build
          # En este paso subimos a la nube la aplicacion q construimos
        - uses: actions/upload-artifact@v3 # Guardamos la carpeta en un ZIP para poder utilizarla en otro sitio 
          with:
            name: dist
            path: dist  
    deploy:
       name: Deploy
       needs: build
       runs-on: ubuntu-20.04
       if: github.ref == 'refs/heads/main'

       steps:
         - name: Download artifact
           uses: actions/download-artifact@v3
           with:
             name: dist
             path: ./dist

         - name: Deploy to GitHub Pages
           uses: peaceiris/actions-gh-pages@v3
           with:
            github_token: ${{ github.token }}
            publish_dir: ./dist       

  